### ISSUE TITLE
Certain Keybinds stop working after downloading subtitles.

### ISSUE THREAD

**Issue by AziRizvi** [tomasklaen/uosc#1026]
MPV Version: v0.38.0-743-gad7976c3
Windows Version: Windows 10 22H2
Script Version: 5.6.2

In my input.conf I have a keybind that I use to cycle different speeds `Shift+| cycle-values speed 2.35 2.65`.
After using UOSC to download subtitles and then clicking anywhere on the video to dismiss the download subtitles box, if I try to use this keybind, it just does not work, same thing happens if I try to open the console with its default keybind, hitting a control button that opens the video/subtitles/audio tracks menu and then dismissing it afterwards seems to solve the issue immediately and then the keybinds start to work again, this issue only seems to be happening with these two keybinds, rest of the keybinds and all seems to work absolutely fine.

To troubleshoot, I purged all of my scripts except UOSC and tested this issue with a new mpv version v0 39.0-327-gca7aeb71 and I got the same behaviour.

**Comment by tomasklaen** [comment]
Same issue as #1025.

I'll close this one and reopen that until it's fixed since it has more info.

In brief: on recent mpv builds, asynchronously spawning our ziggy utility binary for downloading subtitles messes up with mpv's keybinds. Nothing I can do about it on my side unfortunately. Report to mpv if it isn't already please.
