### ISSUE TITLE
how to create `autocreate-playlist` controls shorthand

### ISSUE THREAD

**Issue by candrapersada** [tomasklaen/uosc#1037]
https://mpv.io/manual/master/#options-autocreate-playlist

**Comment by tomasklaen** [comment]
Hot to create control buttons is extensively documented in the default config file.

```
cycle:{icon_name}:autocreate-playlist:no/same!?Autocreate playlist
```

But this is pointless, since it'll change the `autocreate-playlist` value only for the already opened instance, which means AFTER the setting already created a playlist from adjacent files in the directory (if it's enabled). If you want to change the behavior of this option, you need to do it in `mpv.conf`. Adding a button for it into controls bar makes no sense.
