### ISSUE TITLE
Add timeline_chapters_color option

### ISSUE THREAD

**Issue by 63OR63** [tomasklaen/uosc#126]
It would be nice to have an option to change the color of timeline chapters, I don't like how they turn to black on almost black background for played video segment. I personally implemented this by replacing
```
local color = chapter_x > fbx and options.color_foreground or options.color_background
```
with
```
local color
if options.timeline_chapters_color == 'foreground' then
	color = options.color_foreground
elseif options.timeline_chapters_color == 'auto' then
	color = chapter_x > fbx and options.color_foreground or options.color_background
elseif options.timeline_chapters_color ~= nil then
	color = options.timeline_chapters_color
end
```
and adding `timeline_chapters_color` key to options object.
I don't mind if you use this code. Sorry for not making a pull request, I'm not a programmer and don't use git.

**Comment by tomasklaen** [comment]
That was a bug fixed in fb279fe. There are a couple more issues with master, I'll hopefully finish fixing today.

**Comment by 63OR63** [comment]
That's good, though adding some customizability won't hurt in my opinion. Thanks.

**Comment by tomasklaen** [comment]
It'd have be 2 options because you need a different color for when the chapter is above the progress bar/line, as you'd loose contrast in one of the cases. And I'm trying not to have a configuration line for every pixel on the screen 🤐.

I think less configuration fatigue is more valuable here than customizing something this trivial.

But if this gets a significant support I'll reconsider. Until than I'll keep this closed.
