### ISSUE TITLE
Title miss hovering in top left corner

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [tomasklaen/uosc#130]
The title disappears when move the pointer to the upper left corner. Need to test in fullscreen mode.

https://user-images.githubusercontent.com/50797982/186656041-659af825-0193-44ab-9585-113e6c242e88.mp4

**Comment by tomasklaen** [comment]
Yes this is on purpose. I noticed that when I start the player on linux machine, it always displays the title, because cursor position before the cursor moves is reported as `0,0`, even thought it's not.

To fix that, I hardcoded the proximity code to recognize `0,0` as infinity. I thought none will even mind or notice this one pixel in the left top corner hiding the title. I guess I was wrong 😞.

Do you really mind so much that this is an issue for you? If you just want to quickly see the title, you can always just throw the cursor up, and not up AND left.

**Comment by tomasklaen** [comment]
Nvm, I'll fix it in a different way.
