### ISSUE TITLE
Mouse movement triggers the keyboard shortcuts re-render

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [tomasklaen/uosc#131]
`text_width_estimate` was triggered by mousemove.

![image](https://user-images.githubusercontent.com/50797982/186658040-40f9d3d8-5ba0-4a75-9dbb-3db4297a5262.png)

https://user-images.githubusercontent.com/50797982/186657579-11204a03-41b6-4fd3-b52b-096939293ab5.mp4

**Comment by tomasklaen** [comment]
Yeah, `text_width_estimate()` is used in rendering the menu to determine how big it should be and where to clip its elements (so hints don't overflow above titles).

And since this is an immediate, not retained mode UI, it redraws everything any time any data that effects it changes, and cursor position is one of that data. Which isn't an issue, as it's pretty fast to render a couple rectangles.

So I don't see an issue here.

**Comment by hooke007** [comment]
I guess his meaning is too many annoying console-msgs?

**Comment by tomasklaen** [comment]
I don't see any leftover debugging `msg.warn` in there, this has to be his fork.

**Comment by Natural-Harmonia-Gropius** [comment]
performance impact here I mean. every move would trigger all shortcuts re-render, but others like menu label calculate only once.

**Comment by tomasklaen** [comment]
Performance is important to me, but I won't over-complicate the code with premature optimizations that won't have any real world effect.

The menu is occlusion culled (only items that are seen are rendered). In your clip for example, there will be 10 calls to `text_width_estimate()` per frame, which is absolutely not a factor.

Total menu width is cached because it's calculated based on all of the items in the menu, which might potentially be expensive.

If you notice or measure an actual performance hit somewhere, I'll be happy to look at it, but your concerns are not justified here.
