### ISSUE TITLE
Scrolldown on volume silder can set volume to -1

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [tomasklaen/uosc#157]
![image](https://user-images.githubusercontent.com/50797982/187747367-3a0ae7f4-082c-4f41-b494-1b1df9ce02f9.png)

**Comment by christoph-heinrich** [comment]
Can't reproduce. Are you using mpv 0.34.1 or latest master?

**Comment by christoph-heinrich** [comment]
the volume option has been introduced with https://github.com/mpv-player/mpv/commit/74dd64e71d7641ac916be0e63471f076f51370af and it was possible to set to -1 from the very beginning. Can't read the commit message as the original repo doesn't exist anymore, but it seems to be intentional.
The code nowadays says that [volume <0 is ignored](https://github.com/mpv-player/mpv/blob/04062b6f897960938649047c3e2c5ceb08bae295/options/options.c#L635-L637), so maybe just set to 0 in the interface if it is -1?

**Comment by Natural-Harmonia-Gropius** [comment]
Change following to `mp.commandv('set', 'volume', math.max(math.min(new_volume, state.volume_max), 0))` I think. But I'm not sure what does the fourth segment do, seems like it's a method of speed element.
https://github.com/tomasklaen/uosc/blob/1585bc30aaa5bf357dc98e75a4f65a96d4b097c5/scripts/uosc.lua#L2568
https://github.com/tomasklaen/uosc/blob/1585bc30aaa5bf357dc98e75a4f65a96d4b097c5/scripts/uosc.lua#L2582
https://github.com/tomasklaen/uosc/blob/1585bc30aaa5bf357dc98e75a4f65a96d4b097c5/scripts/uosc.lua#L2586
https://github.com/tomasklaen/uosc/blob/1585bc30aaa5bf357dc98e75a4f65a96d4b097c5/scripts/uosc.lua#L2682

**Comment by christoph-heinrich** [comment]
I've asked mpv devs in IRC and they are not too fond of changing it in mpv itself, because it has been like that since forever and who knows what unintended side effects that might have. So changing it in uosc it is.
