### ISSUE TITLE
Speed proximity tied to timeline

### ISSUE THREAD

**Issue by po5** [tomasklaen/uosc#183]
More of a performance issue/dumb edge case than an actual concern.

Despite speed now being part of the control bar, its proximity still gets updated when close to the seekbar.  
Can observed with `controls_margin=200`

Hover near controls
![image](https://user-images.githubusercontent.com/42466980/189492477-e52013db-e9ef-4e83-8937-bec37beb0059.png)

Hover near seekbar
![image](https://user-images.githubusercontent.com/42466980/189492487-254113df-5433-4bd4-be3e-219b9d6e9d8c.png)

**Comment by tomasklaen** [comment]
Yes speed inherits timeline's visibility so that it's displayed when you peek the timeline, as I think they're closely related and personally often use the `peek-timeline` command to check the two.

Putting elements in the middle of the screen with insane margins is definitely not going to be a supported use case.

**Comment by tomasklaen** [comment]
I guess question answered?
