### ISSUE TITLE
[Feature request] Option to open submenu by mouse hover

### ISSUE THREAD

**Issue by junguler** [tomasklaen/uosc#217]
older versions of the osc (which i'm very used to) didn't show sub-menus by hovering my mouse over it, now that they show it my mind always wants to hover my mouse over to open but it just hides the sub-menu if i don't click

so what i want (if possible) is either an option to remove the preview so i can click on the menu i want to get into the sub-menu of (like it used to be) or add an option to keep hovering and only click when i am at my destination

thanks again

**Comment by tomasklaen** [comment]
> my mind always wants to hover my mouse over to open 

Yeah I know, it bothers me too, but here's the deal. We can't render menus outside of the window boundaries. Allowing hovering submenus to the right would clip them out of the boundaries, therefore the controlled menu has to always be in the middle.

I find it valuable to be able to peek a submenu before opening it, and the reflex to hover instead of click is actually just a tiny learning curve, and when you get used to it it's not an issue anymore.

The alternative is to disable peeking when submenu is hovered with a mouse, and only allow it for keyboard navigation. But I'm undecided what is worse, loosing the ability to peak when hovering with a mouse, or imposing the learning curve of click to control the menu on people.

**Comment by junguler** [comment]
i see, thanks for your detailed reply, your reasoning makes complete sense to me and i agree with your approach, feel free to close this issue whenever you want

**Comment by po5** [comment]
A good compromise would be to allow hovering to the previewed menu but keep it grayed out, and clicking on it would bring it to the middle.

**Comment by tomasklaen** [comment]
That would be nice, but I wonder if it's worth it. I'm not sure if there's a simple way to implement it in current codebase. Maybe if I moved cursor item selection/clearing to render loop. I'll keep it on a to-do list and look into it some time.

**Comment by tomasklaen** [comment]
Commit above makes a lot of menu cursor navigation improvements, including selecting submenus:

https://github.com/tomasklaen/uosc/assets/47283320/af7725e2-f9c7-4332-b3e0-8eed966fa45e

**Comment by junguler** [comment]
> not work on my machine.Did I missing something?

try running uosc with default configs (rename your uosc.conf) and see if it's something in your config file that is messing things up 

if that didn't help you might be on an outdated version of uosc, try the newest release and use the included config file and modify things to your liking
