### ISSUE TITLE
Add button for looping individual chapter.

### ISSUE THREAD

**Issue by RexAckermann** [tomasklaen/uosc#218]
There are buttons for file loop and playlist loop.So ,I was wondering if there can be a chapter loop button.
I wrote a rough script myself if it helps,

[https://github.com/RexAckermann/mpv-loop-chapter](url)

**Comment by tomasklaen** [comment]
This is too niche to include, but there's nothing stopping you from adding that button yourself.

Create a named instead of forced key binding in your script:

```lua
mp.add_key_binding(nil, 'toggle', loop)
```

And add a button for it into uosc's `controls` config:

```
controls=...,command:all_inclusive:script-binding loop-chapter/toggle?Loop chapter
```

If you are unclear what's going on there, read the docs in the default `uosc.conf` file.
