### ISSUE TITLE
Wrong time calculation due to recent change to timeline

### ISSUE THREAD

**Issue by christoph-heinrich** [tomasklaen/uosc#260]
While I like the idea behind d953b158bf43aa002c01de5ef82b3990321205a6, it messes with which time corresponds to which pixel. That means hovering shows the wrong chapter and thumbnail relative to the displayed chapters and uncached ranges in the timeline, and seeking is also wrong.

https://user-images.githubusercontent.com/8932183/192107189-48c2de7a-1294-47a1-aab9-f71211c94831.mp4

The way I see it we have 2 options here. Either adjust the time calculation to consider that pushing apart of time (and as a consequence always have the same time while the user hovers over the progress line), or revert to the way it was, because then everything lined up perfectly.

**Comment by tomasklaen** [comment]
Definitely not reverting this. I hated how when watching streams the uncached ranges overlapped the minimized line even though we are still well within cached time. The way how this works now is way better.

So I guess we need to make everything else aware of the push. Probably extracting stuff into `timeline:get_effective_line_width()` and `timeline:x_to_time(x)`, and using it where appropriate.

But I don't have time this weekend anymore, and these shifts are barely noticable since when timeline is not minimized the line is just a couple pixels, so I'll look at it maybe on monday. Or if you want to take over :)

**Comment by christoph-heinrich** [comment]
I currently have a few other things to take care of first, but considering how much time I've invested into getting the old behavior completely pixel perfect, I'll want to make sure everything is just right with this as well :wink:.

**Comment by tomasklaen** [comment]
I got a quick fix idea ^. It basically engages the line x coordinate adjustment only when line is different from its maximized size. Now when the user interacts with the timeline, everything is rendered as if the line is infinitely thin, and all is accurate again.

Only ref instead of close as I'm not sure you'll be satisfied with it :) I haven't noticed any issues.

**Comment by tomasklaen** [comment]
I actually prefer this solution, as making it accurate by making everything else aware of the line push would mean for example that chapter indicators would be jumping from end to start of the line during playback. Now they can continue to be positioned at its middle point.

**Comment by tomasklaen** [comment]
Whops, noticed a bug and force pushed over it 👼.

**Comment by tomasklaen** [comment]
This means that ranges might overlap the line again at its maximized size when it's thick enough, but I don't mind that tradeoff as who's going to set its maximized line width at more than 2-3px?

**Comment by tomasklaen** [comment]
Hm... now that I think about it, I _would_ actually like pixel perfect collisions with ranges even at maximized size :/ And chapters jumping issue can be solved by keeping them centered to the line when timeline is minimized.

All right, I'm off.

**Comment by christoph-heinrich** [comment]
> Now when the user interacts with the timeline, everything is rendered as if the line is infinitely thin, and all is accurate again.

Sounds good.

> And chapters jumping issue can be solved by keeping them centered to the line when timeline is minimized

I don't really understand what you mean with that, but with interactions being accurate again this is good enough for now... until I start using it and it bothers me, probably :upside_down_face:

**Comment by christoph-heinrich** [comment]
The only thing I could think of so far regarding moving the chapter indicators was that maybe we could move each point on the diamond as if it was tied to the time underneath it. so e.g. as soon as the progress line would be underneath the left corner of the diamond, that corner gets moved to the other side of the progress bar. The idea being that it looks like the chapter indicator gets pulled to the other side instead of being instantly moved. I'm worried about how good it will look particularly when the timeline is minimized, but might be worth a try.

**Comment by christoph-heinrich** [comment]
https://user-images.githubusercontent.com/8932183/192349266-c5d94182-459b-4530-b2d3-943258b88b05.mp4

Well... I prefer it over chapters that instantly jump and also chapters that don't align with chapter ranges.

**Comment by tomasklaen** [comment]
Yeah I thought about it and what is currently on main seems to be the best compromise. Making line non zero width at all times and everything be aware of it produces too much quirks, such as the video you posted.

**Comment by christoph-heinrich** [comment]
I don't like the way current main works...
Either go all the way or go back, because not having everything perfectly line up with everything else at all times is unbearable.
What's in the video is better then current main imo, but it was only a prove of concept (simply put the coordinates in `lax()`).
I'll keep tinkering with it until I have something where time always lines up with progress line/bar, chapter indicators, ranges and mouse input. Unless you have a better idea of handling chapter indicators, that will also include the indicators from the video.

**Comment by tomasklaen** [comment]
The chapter indicators jumping to line start doesn't bother me _that_ much. The main problem with everything aware of the line width is the cursor shenanigans it introduces.

What do we do when cursor is above the line? Since line cuts the timeline in half, any pixel within the line now equals current time, so clicking anything inside the line won't do anything. The hovered time tooltip is also locked to current time while cursor is above it.

In a situation where user configures the line to heave lets say a constant 20px (line_width = 20, line_width_minimized_scale = 1), this would be annoying.

The kind of a workaround would be for a cursor to treat the line as infinitely thin while it's inside it, but than as you are moving towards the line, the timestamp increases, than you touch it and it decreases back, and matches the time before you touched it only when you reach the center of the line. This is weird.

**Comment by christoph-heinrich** [comment]
Yes, that design comes with a bunch of problems which the previous one didn't. I've now made a draft PR #270 where everything lines up and is consistent. Ignore the code for now, I'll make it pretty tomorrow :wink:, but it's good enough for testing the behavior. Mouse input is kinda weird, but it still bothers me less then current main.

**Comment by tomasklaen** [comment]
But having an always thick progress line is a valid use case that someone might prefer, and it is supported by config, so we have to at least think about it.

**Comment by christoph-heinrich** [comment]
I have been testing with a 29px wide progress line and didn't perceive it as a problem.

**Comment by FichteFoll** [comment]
> If someone actually has a giant display with a high enough resolution that having a 20px wide line makes sense, there will still be plenty of space outside of that for seeking and hovering and again, relative to the rest of the display those 20px are going be thin.

Would it make sense to switch this to a fractional width specified, i.e. percentage of window width? Or would that quickly become unreasonably small for very small windows and unbearably large for maximized/fullscreeen? (I don't use the line myself because I find the bar to be much clearer in UX.)

Additionally, instead of the weird stretching effect I would expect that interpolating the diamond chapter mark's position over the progress line's width as it approaches it would be simpler to process but also require some math to make it feel smoth and not just instantly move over. I could imagine it as a sort of magnifier for the area covered by the progress line.
