### ISSUE TITLE
Replace uncached ranges by cached/seekable ranges

### ISSUE THREAD

**Issue by heuaheuahuehua** [tomasklaen/uosc#351]
when watching something uncached my entire timeline is bloated with stripes and I can't see my timeline instead of showing my cached range with timeline_cached_ranges like before.
![image](https://user-images.githubusercontent.com/71800058/198336174-92e90fe9-5eea-4956-bcc0-7a7c6e75adc2.png)
![image](https://user-images.githubusercontent.com/71800058/198337137-e540fb61-27ff-45c2-8efa-8404edd9cf5e.png)

**Comment by heuaheuahuehua** [comment]
I didn't mean it as a complain, it was more of a suggestion because it covers all of the timeline. but that's understandable, thanks. 
could I paste some of the old code back and still work? I tried but maybe I did something wrong. or maybe could you give me some guidance to remove this texture? I'd appreciate it. 
I like your new changes to the UI so Id like to update, thanks again.

**Comment by christoph-heinrich** [comment]
The code has changed a lot since then. I'm sure it wouldn't be too hard to get working, but you'll have to do that on your own.
The `demuxer-cache-state` property observer needs to be changed to save the cached ranges instead of inverting them to get uncached ones (so simply save what you get from the observer in state).
In the timeline you'll have to then take the old code for drawing the cached ranges, replace the code for uncached ranges.
Use `t2x()` to convert the time of cached ranges into x coordinates.

**Comment by tomasklaen** [comment]
With commit above, set `timeline_cache=no` to just disable the cache indicators if you want.

**Comment by heuaheuahuehua** [comment]
thanks a lot to both of you. 
timeline_cache=no works well for me too.
