### ISSUE TITLE
Add ability to remember which episode is currently being watched

### ISSUE THREAD

**Issue by Zabooby** [tomasklaen/uosc#404]
When I'm watching multiple shows at the same time I sometimes forget which episode I'm on, would you be interested in maybe adding this feature?

It could be as simple as having the current episode preselected, when the playlist menu is opened.

**Comment by tomasklaen** [comment]
I wouldn't honestly. We'd need to figure out how to produce and identify/manage/save/load additional meta for different playlists. Full of finicky behavior.

I just delete episodes I've watched. That's why the `delete-file-next` command exists.

> It could be as simple as having the current episode preselected, when the playlist menu is opened.

That's already happening, no? We always pre-select current item in all menus (directory navigation, playlist, ...).

**Comment by Zabooby** [comment]
I meant it would pre select the episode in the playlist menu when no file is open. Similar to how it works when a file is open.

**Comment by tomasklaen** [comment]
If we had this information this would be trivial. But the problem is getting it, saving it, and loading it for a particular playlist. As far as I know you can't attach a meta data to a playlist. And playlists also don't have IDs, so another problem is to identify them. Just a hornets nest of problems that'd require a lot of bloat to solve for a feature pretty much none will notice.

**Comment by Zabooby** [comment]
Ok I'll close the issue, it was just a minor nitpick.

**Comment by christoph-heinrich** [comment]
Seems to me like that would be better as a separate script. It can still use the menu system from uosc via script messages.

**Comment by dyphire** [comment]
These scripts have already implemented similar functions: [SimpleHistory.lua](https://github.com/Eisa01/mpv-scripts/blob/master/scripts/SimpleHistory.lua), [history-bookmark.lua](https://github.com/dyphire/yuukidach-mpv-scripts/blob/master/history-bookmark.lua)

**Comment by Zabooby** [comment]
> These scripts have already implemented similar functions: [SimpleHistory.lua](https://github.com/Eisa01/mpv-scripts/blob/master/scripts/SimpleHistory.lua), [history-bookmark.lua](https://github.com/dyphire/yuukidach-mpv-scripts/blob/master/history-bookmark.lua)

Wow, [history-bookmark.lua](https://github.com/dyphire/yuukidach-mpv-scripts/blob/master/history-bookmark.lua) is exactly what I'm looking for, thanks for the link!

PS: Is your profile pic the mc from the anime blood blockade battlefront, i feel like I recognise him?
