### ISSUE TITLE
Add `menu` navigation actions/commands

### ISSUE THREAD

**Issue by Jelmerro** [tomasklaen/uosc#415]
I have recently been looking into uosc, and I must say that it's been great so far, except for one small thing, the arrow keys in the menu. Everything else in my mpv config can be controlled with single letters and does not require the arrow keys, except for the uosc menu. To me it seems kind of useless now to have a custom key to toggle the menu, when you then cannot use nearby keys to navigate within it. I did find https://github.com/tomasklaen/uosc/issues/275 and https://github.com/tomasklaen/uosc/commit/f27e17e7dcbe89aa6d3655c8cf2c741c60c1da10, both of which made me kind of sad, but I do understand the reason for their removal: you do not like to maintain multiple sets of keybindings, which I understand. So I suggest to implement a couple of commands to make custom script-bindings to the menu possible, such as `h script-binding menu-back` etc. This would solve the annoying issue of having to use the arrow keys without adding many different sets of binding by default. I really hope you will consider doing so at least for the basic menu actions. Repeating keys are not an essential part of this, even having to press h or w multiple times would be better than holding the arrow up for me, since it's still faster than moving my hand to the arrow just to navigate the menu. Thanks for your time and the great mpv interface!

**Comment by tomasklaen** [comment]
The main reason I wanted menu navigation off the character keys is potentially implementing menu search functionality (for stuff like directory listings, playlists, etc), where people can just start typing and it'll filter the menu automatically. If we allow any keys for menu navigation, then there will have to be a dedicated shortcut to start search.

So I'm not sure what is worse - annoying everyone that wants to search with an extra shortcut, or forcing a couple vim enthusiast to use arrows.

**Comment by Jelmerro** [comment]
Wouldn't it then be possible to make searching without a key an option/setting, and add a new command to start searching for those that disable instant search?

**Comment by FichteFoll** [comment]
Related: https://github.com/tomasklaen/uosc/issues/14 (wow, number 14. It's been a while)

**Comment by omaru-ok** [comment]
> . I did find #275 and [f27e17e](https://github.com/tomasklaen/uosc/commit/f27e17e7dcbe89aa6d3655c8cf2c741c60c1da10), both of which made me kind of sad

@Jelmerro thx, for looking at my issue, and we both thinks that vi based  should be get back , 
or implement the menu navigation as author is thinking

**Comment by XCanG** [comment]
I know it's probably will take a lot of works, but if possible to make a menu in style of "command palette". You can see example right here in Github by pressing `Ctrl`+`K` and look in the docs: https://docs.github.com/en/get-started/using-github/github-command-palette

So that by opening menu and typing menu item it will be shown and be able to select, for example: by pressing hotkey for command palette and type `open`, then hit enter, you will open `Navigation > Open file` menu, then in that menu by typing name you will filter file names and then select one that you need.

This may take a lot of work, but it will speed up navigation a lot.

**Comment by tomasklaen** [comment]
@XCanG sorry for delayed reply, I though I responded to you when I've read it a couple months ago. But yes, <kbd>ctrl+k</kbd> like menu will be possible once I implement menu search. No ETA though.

**Comment by tomasklaen** [comment]
Also, since instantly searchable command menu is on the road map now, it means allowing people to customize menu navigation keys would be incredibly painful to implement and maintain. We'd have to have context switching between input and navigation modes, at which point we are re-implementing vim here, so this issue will have to be a wontfix.
