### ISSUE TITLE
Make Buffered Time change according to playback speed

### ISSUE THREAD

**Issue by NaiveInvestigator** [tomasklaen/uosc#421]
Buffered Time does not change according to playback speed, but time remaining and others change with according to speed tho.

Minor issue, just thought you'd want to know.

**Comment by christoph-heinrich** [comment]
I don't know if this should change or not, because it's just a matter of perspective, but I've always understood the `buffered_time_threshold` option to be "the largest number that should be shown".
If it's actually intended as such, then we should scale the time before the `buffered_time < options.buffered_time_threshold` check, because otherwise speeds > 1 won't show numbers up to the configured `buffered_time_threshold` and speeds < 1 will show numbers bigger then that.

**Comment by christoph-heinrich** [comment]
Since I'm not the only one to interpret it this way, I've made a PR to try it out.
