### ISSUE TITLE
[ffmpeg] NULL: Invalid NAL unit size ?

### ISSUE THREAD

**Issue by lavara123** [tomasklaen/uosc#446]
Some videos freeze after 3 seconds and when I close them, I see this error in the terminal
```diff
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: Packet corrupt (stream = 1, dts = 114000).
- [ffmpeg] NULL: Invalid NAL unit size (9936 > 761).
- [ffmpeg] NULL: missing picture in access unit with size 765

```

Sample video:
http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4

**Comment by christoph-heinrich** [comment]
That has nothing to do with uosc. You should open an issue in the [mpv issue tracker](https://github.com/mpv-player/mpv/issues) about this, including a log file obtained with `--log-file=log.txt`.

**Comment by lavara123** [comment]
> That has nothing to do with uosc. You should open an issue in the [mpv issue tracker](https://github.com/mpv-player/mpv/issues) about this, including a log file obtained with `--log-file=log.txt`.

It works fine with `mpv --no-config` ?

**Comment by christoph-heinrich** [comment]
Then you have to find out which part of your config is at fault. It's probably something in your `mpv.conf`, so start by deleting half of it and see if the problem persists. Once you found which option causes problems for you, open an issue about it on the mpv issue tracker.

You might prefer creating a temporary config for that and instead of deleting parts of your config, you add parts of your original config. `--config-dir=<path>` is useful for that.

**Comment by lavara123** [comment]
@christoph-heinrich 
@tomasklaen 

i discovered something
I get the same error if I use the -v trace flag using ffplay

`ffplay -v trace 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'`
