### ISSUE TITLE
auto play the next video in the playlist

### ISSUE THREAD

**Issue by jafri-jahan-s** [tomasklaen/uosc#464]
Is there an option to make the player play the next video once the current video ends so doesn't have to press the hotkey to go to next file every time? if yes, please tell me how to enable it, and if not, please consider adding this feature because it would be useful when watching long series with lot of episodes. 
also its really frustrating to see features that work straight forward in linux  doesnt work in windows like selecting multiple files and just hitting enter starts a the videos in a single window as a playlist in linux but in windows all the videos open in separate windows which is really frutstrating to me. i recently came back to windows after using linux for a few years and its really frustrating.
so thank you for implementing the playlist feature

**Comment by BhaturaGuy** [comment]
In `uosc.conf` add this: `autoload=yes` 
In `mpv.conf` add this: `keep-open=yes`
or this use this script alternatively [autoload.lua](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua)

**Comment by cipricus** [comment]
A playlist is already playing next track, of course. But you don't have a playlist unless you opem/load multiple files in mpv.

Please read the file `uosc.conf` (`~/.config/mpv/script-opts/uosc.conf` in Linux)

The button you see on the screen is not just for playlist, but refers to the option `items`, which shows a playlist if there is one loaded, but otherwise acts as file browser. Probably you are confronted with the case where you don't have a playlist but you want the files listed there (the ones in the same folder) to be played as in a playlist. That is achieved as said in the other answer, as per `uosc.conf`:
```

# If there's no playlist and file ends, load next file in the directory
# Requires `keep-open=yes` in `mpv.conf`.
autoload=yes
```

To just see the playlist, the file browser (open file option), the "items" mentioned above, list/load subtitles etc  you can add shortcuts (even buttons but thst I don't know how exactly). You have to add to `input.conf` lines like these:

```
Ctrl+p script-binding uosc/playlist
o script-binding uosc/open-file
Ctrl+s script-binding uosc/subtitles
p script-binding uosc/items
```
