### ISSUE TITLE
change uosc timeline to modernx timeline

### ISSUE THREAD

**Issue by bachig26** [tomasklaen/uosc#466]
**https://github.com/cyl0/ModernX**

I like how the ModernX timeline looks. is there any possibility to change the uosc timeline to that? how can i configure that if i can do without any new changes in the uosc itself?

**Comment by tomasklaen** [comment]
This is the weirdest request yet. Would you write a support ticket to macOS to make their UI look like Windows because you like that more?

If you like ModernX, just use ModernX.

But to actually answer: from my point of view and what is important to me - there are so many UX and information density issues with a thin line as a timeline that I'll never consider doing it in uosc. If you don't agree with uosc's design direction, it's fine, just use one of the alternative UI's out there.
