### ISSUE TITLE
add BufferingIndicator option to uosc.conf

### ISSUE THREAD

**Issue by bachig26** [tomasklaen/uosc#467]
```
# Can be: none, flash, static, manual (controlled by flash-pause-indicator and decide-pause-indicator commands)
pause_indicator=none
```
as I have looked through the `~/script-opts/uosc.conf`, I can't find an option to enable/disable the `BufferingIndicator.lua` similar to the `PauseIndicator.lua`.

**this issue is to request for including an option to enable and disable by manually.**

**Comment by tomasklaen** [comment]
You want an option to make the UI/UX worse?

When video freezes, you want to be uncertain as to what is happening (part of the video, end of the video, buffering, ...) instead of getting a clear indicator that the stream is buffering?

I don't like bloating the config file with options that don't add much value, and I don't see any here honestly.
