### ISSUE TITLE
Add options to completely disable Fade In/Out Animation

### ISSUE THREAD

**Issue by GunGunGun** [tomasklaen/uosc#471]
Some people including me don't like fade in/out animation and just want instant UI result, I tried to disable most of the animation but there's still Menu's fade in/out and switch animation that I can't seem to disable, should we consider adding an or few option(s) to disable them ?

**Comment by tomasklaen** [comment]
Really? The animations are like 2-3 frames long...

I hate long animations too, but no animations are also bad because it's confusing when UI just instantly changes with no indication where things went. For example, when you go into a submenu, you might fail to notice that the navigation actually happened if the submenu looks too similar to the parent menu, but it's clear if there's a couple frames long animation of parent menu animating to the left.

You're essentially asking me to put in an effort and add more complexity to the codebase to produce a worse UX.
