### ISSUE TITLE
Option to behave as normal osc without proximity

### ISSUE THREAD

**Issue by Eisa01** [tomasklaen/uosc#48]
While the proximity is functioning properly and I did not encounter issues with it,
I would like to have the option that all elements appear on mouse movement, exactly as the normal OSC. 
So it would behave like the normal OSC but with the advantages of uosc.

**Comment by darsain** [comment]
I wouldn't *mind* having this as an option for people, but I personally hate every player that works like this (one of the main reasons I made uosc), so I can't see myself working on this any time soon.

**Comment by Eisa01** [comment]
Very true, you would not have created the proximity otherwise. Developing OSC script is complex enough to give me headaches. Since that option is not coming any time soon, is there any way I could extract the volume seekbar from this OSC and import it into the default OSC that mpv provides? 
I have attempted various times, but I cannot seem to avoid the conflict.

**Comment by t-mart** [comment]
Plus one for this feature.

In the meantime, a workaround is just setting very large `proximity_in` and `proximity_out` values. Bigger than the largest dimension of all your monitors, at least.

Example:

```
# distances in pixels below which elements are fully faded in/out
proximity_in=10000
proximity_out=10000
```

If the feature were to be implemented, an idea may be to recognize the setting of these values to `-1` to trigger the showing of the elements, an otherwise nonsensical value.

**Comment by allmeta** [comment]
@t-mart I'm having an issue with that. Entering fullscreen makes the UI visible until I move the mouse.
This is with auto-hide enabled ofc.
Are you experiencing anything similar?

**Comment by t-mart** [comment]
@allmeta, this could be so. Unfortunately, I no longer use this UI and cannot confirm.

**Comment by allmeta** [comment]
To anyone else having trouble with this, this fixed it for me.
add this patch to `uosc.lua`
```diff
@@ -1345,6 +1347,7 @@ function update_display_dimensions()
        -- Some elements probably changed their rectangles as a reaction to `display_change`
        update_proximities()
        request_render()
+       handle_mouse_leave()
 end
```

**Comment by FichteFoll** [comment]
You could also bind a key to `script-binding uosc/peek-timeline` and use that to toggle the timeline in any state.

**Comment by tomasklaen** [comment]
So after some thinking, here's the verdict: I won't be bloating the code of a proximity based UI to not be proximity based.

If you move your cursor, you should be doing that because you want to control the UI with it.

If you want the UI to hide after cursor becomes idle, use `autohide=yes`. (personally I find this annoying)

If you want to peek the UI during playback to check time, speed, volue, title, etc... I just added `peek-ui`, or individual `peek-volume`, and `peek-top-bar` commands (along with already existing `peek-timeline`), so bind them as suggested above. I also use the `tab` key and can recommend, it's a nice feature. Way better than shaking a mouse, or tickling a trackpad, as you don't have to wait for it to disappear, just pres the `tab` again and it's gone. You are in a complete control of when and for how long it stays visible.

**Comment by tomasklaen** [comment]
Another revision. All of the `peek-{x}` commands were renamed to `toggle-{x}`, and they toggle the permanent min visibility of elements they are attached to between `0` and `1`.

This means the visibility triggered by these commands is no longer reset by mouse movement.

Mouse resetting it was annoying, and I've realized there was no good reason for it.
