### ISSUE TITLE
Display thumbnails and cover art in menus

### ISSUE THREAD

**Issue by AKL55** [tomasklaen/uosc#487]
Is it possible to display cover art on mpv like this
![ykjrhghshsehse](https://user-images.githubusercontent.com/89634553/228578811-8410f4e6-58e2-4f01-82b0-97f8689ec132.png)

![2222](https://user-images.githubusercontent.com/89634553/228579090-f4580ced-9156-4b67-a6a3-cfb7fb19a23b.png)

**Comment by tomasklaen** [comment]
Technically: yes

Practically: due to the nature of the environment we are working with and its constraints, this would require **a lot** of work, hacks, workarounds, and not add any new meaningful functionality, just a bit of an eye candy.

In other words, I wouldn't work on it unless someone payed me. So for the foreseeable future, this is not planned.
