### ISSUE TITLE
Online subtitle search

### ISSUE THREAD

**Issue by tazihad** [tomasklaen/uosc#490]
Maybe it's a bit too much for minimal ui. I was thinking is there any way to search subtitle online?

**Comment by christoph-heinrich** [comment]
I'm pretty sure there are already scripts that can search/download subtitles. Those scripts can use the menu aPI that uosc provides for better integration.

**Comment by tomasklaen** [comment]
I really want this in uosc as well. This is exactly why I added support for spinner icons in menu items (displaying loading indicator while fetching subtitle data). But when I was thinking about writing it a couple months ago, I haven't found a good subtitle provider with an open API that would make it easy, and I don't feel like hacking together html parsers, and dealing with captchas, and extractors breaking every time they change html structure or rename an html class/id.

If someone makes something that integrates with uosc, I'll gladly add it to install instructions.

**Comment by omaru-ok** [comment]
i would like to add some material required here : 
* ⭐ **[Open Subtitles](https://opensubtitles.org/)** - Subtitles
 * [Podnapisi](https://www.podnapisi.net/) - Subtitles
* [Subsplease](https://subsplease.org/) - Subtitles 
* [opensubtitles.com](https://www.opensubtitles.com/) - Subtitles
* [HandySub](https://github.com/HandyOrg/HandySub), [SubDownloader](https://subdownloader.net/) or [Subscene-Subtitle-Grabber](https://github.com/RafayGhafoor/Subscene-Subtitle-Grabber) - Subtitle Downloader
* https://subask.com/    
* https://subask.com/
there is so many more

**Comment by BhaturaGuy** [comment]
> * [opensubtitles.com](https://www.opensubtitles.com/) - Subtitles

SubsPlease doesn't provide subs, [animetosho](https://animetosho.org/) is the one that provides anime subtitles, but using that would be quite complicated, since anime subs are usually `.ass` which do require fonts to properly display subs, not to mention that it gives subs + their fonts in `.7z` archive.

So the required output would be something like this.
1. Download `.7z` archive.
2. Extract it somewhere, media file's location preferably.
3. Change the name of the sub file from `track{track_id}_{slang}.ass` to `mediafile name_{slang}.ass`.
4. Then move the files in `attachments` folder to somewhere where mpv can parse them without installing them, `~~/fonts` maybe?
5. Then reload mpv with all the settings intact (playtime, profiles, filters, etc).
6. Then use `slang` priority order in `mpv.conf` or [sub-select](https://github.com/CogentRedTester/mpv-sub-select) to select sub and play.

Since I am not an engineer I can only imagine how much tough this would be, but then again maybe anime sub support isn't required at all since "why would someone download anime without subs?"

**Comment by gunir** [comment]
> i would like to add some material required here :
> 
>     * ⭐ **[Open Subtitles](https://opensubtitles.org/)** - Subtitles
> 
>     * [Podnapisi](https://www.podnapisi.net/) - Subtitles
> 
>     * [Subsplease](https://subsplease.org/) - Subtitles
> 
>     * [opensubtitles.com](https://www.opensubtitles.com/) - Subtitles
> 
>     * [HandySub](https://github.com/HandyOrg/HandySub), [SubDownloader](https://subdownloader.net/) or [Subscene-Subtitle-Grabber](https://github.com/RafayGhafoor/Subscene-Subtitle-Grabber) - Subtitle Downloader
> 
>     * https://subask.com/
> 
>     * https://subask.com/
>       there is so many more

Great list, but I want to add Subscene because I think this website is very "easy", compare to OpenSubtitles which requires users to login and do captcha, this one is pretty loose.

**Comment by NormTurtle** [comment]
> I want to add Subscene

i think instead of adding * particular to the list i now directly link to a place which contain most of info possible related to piracy 
https://fmhy.pages.dev/videopiracyguide/#subtitles

note : this maybe bad 💀 that im saying , yes im a member and i have done some contribution to there list and thus still , you can give me improvements on that wiki too

**Comment by gunir** [comment]
@christoph-heinrich Is is possible to bring socket support to MPV's lua ? With socket captability we can write much much better network code instead of relying on curl, aria2c.... And calling subprocess which is slow.

I don't understand why most programming languages have a socket library but lua doesn't

I consider this a big jump in terms of usability.

**Comment by christoph-heinrich** [comment]
@gunir I'm sure it's possible, but if you want that in mpv then the uosc issue tracker is the wrong place to ask :wink:

**Comment by FichteFoll** [comment]
@gunir you may be looking for https://mpv.io/manual/master/#json-ipc.

**Comment by kasper93** [comment]
Neat feature. Although I personally don't use subtitles it nice to have an option to search them quickly should you need them.

Do you consider adding more providers in the future? Specifically I find `podnapisi.net` way more useful than `opensubtitles` in both the quality and availability of subtitles. YMMV depending on language, but form my limited experience podnapisi serve me better.

**Comment by tomasklaen** [comment]
Afaik there are no other subtitle providers with an API endpoints, and I'm not maintaining html serializers and trying to work around rate limiting, captchas, and stuff like that.

**Comment by kasper93** [comment]
> Afaik there are no other subtitle providers with an API endpoints, and I'm not maintaining html serializers and trying to work around rate limiting, captchas, and stuff like that.

No, no, of course not. I would not suggest anything like that.

They provide XML API. Maybe it is not advertised well, but it is documented on forum here https://www.podnapisi.net/forum/viewtopic.php?f=62&t=26164#p212652.

Client that we added in MPC-HC 8 years ago is still working fine today. There is no captcha, login requirement, etc. Not sure if it uses latest api version, but it still works. They also support the same hash as opensubtitles.
https://github.com/mpc-hc/mpc-hc/blob/e37826845859bfbc360989aaef3807ef15a83768/src/mpc-hc/SubtitlesProvider.cpp#L548-L764

Apparently there is also JSON API https://github.com/Diaoul/subliminal/issues/916#issue-319478609 (MasterMind2k is podnapisi admin)

If you would be interested in adding it, I guess you can ping MasterMind2k with any questions. I don't want to summon him here prematurely :)
