### ISSUE TITLE
Line timeline style offsets chapter markers

### ISSUE THREAD

**Issue by po5** [tomasklaen/uosc#550]
Reproduction steps:
- `timeline_style=line`
- Open a file with chapters
- Click around different chapters

Chapter markers get nudged to the left/right.

**Comment by christoph-heinrich** [comment]
That is intentional. It happens because time is decided up to be entirely either before or after the line indicating the current playback position. That progress line itself doesn't "take up" any time itself.
Here is a related issue I opened shortly after the timeline change that ended up leading to what we have today #260.

**Comment by po5** [comment]
> I hated how when watching streams the uncached ranges overlapped the minimized line even though we are still well within cached time.

This won't be an issue anymore with #548? Though I haven't pushed the code for adding progress line to the \clip yet.

**Comment by christoph-heinrich** [comment]
\clip only works on integer coordinates while the progress line uses values in between for smoother movement.
Does it still use fine with that?

**Comment by po5** [comment]
\clip and \p allow for a scale factor (here, 4, as that's what everything uses internally), which allows for higher precision. It does look fine.

**Comment by po5** [comment]
I find it especially annoying when `timeline_line_width_minimized_scale != 1` because you see all chapters shift at the same time.

**Comment by tomasklaen** [comment]
So yeah, I still maintain that the current behavior is the best compromise with the least amount of issues.
