### ISSUE TITLE
Toggle top bar controls individually 

### ISSUE THREAD

**Issue by yonikek** [tomasklaen/uosc#574]
It would be nice to have the option to toggle the top bar controls individually. Especially to have only the close button to fit in better with the Gnome desktop environment.
![Screenshot from 2023-06-12 04-02-48](https://github.com/tomasklaen/uosc/assets/92832837/07e48887-c7c1-4b76-bce5-a3bafd55e45c)
See pic if not clear enough.

**Comment by po5** [comment]
Is this what you're looking for? https://github.com/tomasklaen/uosc#flash-ui

**Comment by tomasklaen** [comment]
No, he wants minimize and maximize buttons removed from the top bar.

It's an ask to increase configuration fatigue for everyone to cater to <1% of users.

I'm not against skipping rendering these buttons in environments that don't need them, but if the only way to do that is more configuration (to a config file that is not far from or already intimidating) because we can't easily and reliably detect these, that I'm leaning against it.

**Comment by yonikek** [comment]
Yes that's what I meant.

Fair enough if you don't want to overcomplicate things. I can live with commenting out a couple of lines of lua but I figured some users probably wanted to remove the min/max buttons and gave up when they couldn't find an option.

**Comment by FichteFoll** [comment]
There is an option already to remove all buttons there and I use it because of my tiling window manager not showing any such decorations. It *could* be re-used to say which buttons to render exactly instead of just toggling this behavior, but the use case seems to be very minimal. I generally use `q` to close mpv so I never missed also not having a close button.

https://github.com/tomasklaen/uosc/blob/442fe6b2e566dbf1e60f97e722bd3917c0c80156/script-opts/uosc.conf#LL124C21-L124C21
