### ISSUE TITLE
clarify gpl3 variant

### ISSUE THREAD

**Issue by nekopsykose** [tomasklaen/uosc#586]
the gpl-3.0 licence comes in two forms (technically more per spdx for linking exceptions, but that's not relevant here):

- -only  
- -or-later  

this is generally differentiated by following the following section:  

```
  If you develop a new program, and you want it to be of the greatest
possible use to the public, the best way to achieve this is to make it
free software which everyone can redistribute and change under these terms.

  To do so, attach the following notices to the program.  It is safest
to attach them to the start of each source file to most effectively
state the exclusion of warranty; and each file should have at least
the "copyright" line and a pointer to where the full notice is found.

    <one line to give the program's name and a brief idea of what it does.>
    Copyright (C) <year>  <name of author>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
```

and then either having that header, or omitting the 'or any later version' (omission of which makes it -only, per spdx).

using an spdx identifier (`GPL-3.0-only`, `GPL-3.0-or-later`, ..) somewhere to pick one (instead of just copying around full headers) also generally works.

which one is this project intended to be assumed as (for licensing clarity)?

**Comment by tomasklaen** [comment]
I hate dealing with this legal stuff :( I only added the license because #53 requested it. GPL 3 seemed like a good choice, but I'm not really familiar with all the license differences and tradeoffs. What is the minimum that needs to be done to make it valid? I don't want to add a license block to every file, and I don't want to be incrementing a year number every January. What are your recommendations? Re-license to something else? WTFPL?

My priorities from highest to lowest:

1. **I don't want to be sued if uosc messes something up**
1. **Zero maintenance**
    Doesn't require current year in license file, or a header in every source file in repo.
1. **Don't want people to steal it and make money off of it without giving back**
    But I might drop this requirement if it'd mean I don't have to deal with license stuff again.

**Comment by christoph-heinrich** [comment]
The last time I looked into it I preferred GPLv2 over v3, but I don't remember the exact reasons why (they added some weird stuff that they didn't publicly disclose or something). I'd be fine with re-licensing to GPLv2, but you'd have to get permission from everyone that has contributed.

**Comment by tomasklaen** [comment]
> have to get permission from everyone that has contributed

Oh my god I hate this too :( So now I'll have to bug people about this dumb stuff. Need a license that doesn't have this kind of requirements.

Wanting to satisfy someone's request to have a license made me put my project into a state where I can't do certain things with it. This is like getting burned by not reading the fine lines on a deceptive contract. Why do we have a world where you need to be a lawyer to not get screwed from one end or the other... I just want to make useful stuff. This is burnout fuel.

**Comment by nekopsykose** [comment]
> I hate dealing with this legal stuff :(

me too :/ i feel like a bit of devil advocate sometimes, doing it solely from the perspective of a distro maintainer, labelling software.

> I don't want to add a license block to every file, and I don't want to be incrementing a year number every January. What are your recommendations?  

if adding 'just' one line of text to every file is an option (technically a header), then just `-- SPDX-License-Identifier: GPL-3.0-???` theoretically works.

barring that, just putting that in the readme/etc "works for me" (and i doubt anyone is going to care past that, seeing it clearly spelled out in one place). usually projects with a build system (meson.build, Cargo.toml, ...) have a license: field where someone puts this (and then not into any file), and in general nobody cares, so ehh...

and, barring that, you can of course pick a licence that does not require any headers or somesuch to disambiguate types (apache-2.0, wtfpl, ... (most of them)).

> have to get permission from everyone that has contributed 

for specifying purely `GPL-3.0-only`, i don't think you'd have to, as it's not technically a relicense i don't think

**Comment by christoph-heinrich** [comment]
> Need a license that doesn't have this kind of requirements.

yt-dlp has something in their PR template that essentially says "you give up any rights to any code you contribute", so they can then do whatever they please with it.

**Comment by FichteFoll** [comment]
I'm not a fan of copying licence headers into each file either. I prefer to have a `LICENSE` file with that part instead, which for the GPL would be the section quoted in OP. I would then rename the current `LICENSE` to just `LICENSE-GPL3.txt` or similar so that it is included in the repo but distinct from the actual license text used for the project.

Updating the copyright year should be optional in general. The only "problem" I see for the current situation is that there was no copyright holder declared for this repo according to the license since it just holds the template. Something along the lines of "Tomas Klaen & uosc contributors" would work, though. I also agree that the current license could be interpreted as "GPL-3.0-only" as the opt-in for the later versions hasn't been specified explicitly.

IANAL.

**Comment by tomasklaen** [comment]
I'll probably be re-licensing to something more permissive, as I don't like the idea that I have to ask everyone that contributed if I can do something with my project, but since this is one of the last things I want to spend my time on, I don't know when I'll get to it.

And was the license even in effect when none of the descriptions, author name, etc was filled in the template? Can I just change it without bugging anyone?

Suggestions for a new license welcome. ([requirements above](https://github.com/tomasklaen/uosc/issues/586#issuecomment-1640563755))

**Comment by christoph-heinrich** [comment]
Afaik re-licensing always requires permission from everyone (unless you have something like yt-dlp in place), no matter if it's to something more or less restrictive, because technically that code belongs to their authors and so you can't just change the license of their code.
Please someone correct me if I'm wrong, I'm far from an expert on that.

I agree with @FichteFoll that without explicitly opt-in for later versions, the current license would be considered 3.0-only.

My vote is for GPLv2, but if you want to go with something else, I won't stand in your way.
