### ISSUE TITLE
`main.lua:975: attempt to index a nil value` when opening a playlist

### ISSUE THREAD

**Issue by musjj** [tomasklaen/uosc#590]
```
[uosc] 
[uosc] stack traceback:
[uosc] 	...uosc-unstable-2023-07-19/share/mpv/scripts/uosc/main.lua:975: in function 'serializer'
[uosc] 	...unstable-2023-07-19/share/mpv/scripts/uosc/lib/menus.lua:51: in function 'callback'
[uosc] 	...uosc-unstable-2023-07-19/share/mpv/scripts/uosc/main.lua:902: in function 'fn'
[uosc] 	mp.defaults:230: in function 'fn'
[uosc] 	mp.defaults:65: in function 'handler'
[uosc] 	mp.defaults:380: in function 'handler'
[uosc] 	mp.defaults:510: in function 'call_event_handlers'
[uosc] 	mp.defaults:552: in function 'dispatch_events'
[uosc] 	mp.defaults:503: in function <mp.defaults:502>
[uosc] 	[C]: in ?
[uosc] 	[C]: in ?
[uosc] Lua error: ...uosc-unstable-2023-07-19/share/mpv/scripts/uosc/main.lua:975: attempt to index a nil value
```

Sorry if there isn't much information here, but I noticed that this only happens on NixOS. It works just fine when I was on Arch and Windows. Tested both on `4.7.0` and 72982e29b3c21929807db3ded30ec79462a40469.

I'm assuming that `item` turns out to be `nil` here:

https://github.com/tomasklaen/uosc/blob/72982e29b3c21929807db3ded30ec79462a40469/scripts/uosc/main.lua#L969-L975

No idea why that would happen though.

EDIT: I think I narrowed down the cause. This error happens only when the filename contains certain characters. I have video files with names containing ISO timestamps like `2023-06-23T12:55:20+01:00`, which are totally valid filenames on Linux. I guess this plugin tripped over some of those characters.

**Comment by tomasklaen** [comment]
Damn, I forgot about this issue completely.

It seems to me like the presence of `:` in the path was triggering `is_protocol()` check, which caused `serialize_path()` to return `nil`.

But since then we refactored the checks in `is_protocol()`, and fixed this by accident, so I'm gonna close this.

Though I suspect the match for magnet like URI schemes (`magnet:?`) can still hit a valid path, since on linux both `:` and `?` are allowed in file names, but I don't think there's much to be done about this, apart of hoping none makes filenames like that :)
