### ISSUE TITLE
What protocol is this function trying to match?

### ISSUE THREAD

**Issue by musjj** [tomasklaen/uosc#605]
This particular function raised false positives for a few of my files that contains colons:

https://github.com/tomasklaen/uosc/blob/bc7b1a12bce15c069947e3bc2f01df757865c6dd/scripts/uosc/lib/utils.lua#L321-L323

I understand the point of the first pattern, but what kind of protocol `^%a[%a%d-_]+:\\?` is trying to match?

Alternatively, can't we just use `utils.file_info(path)` to check if it is a valid local path? Or would that be too expensive?

**Comment by tomasklaen** [comment]
That came from #336, it's checking for stuff like `magnet:?`.

The purpose of this function is to determine if path is a local path or a url, since they need different handling. We can't do this with file info since local paths that don't exists should also return `false`, and I don't know if we're using this while listing directories, but if so, it'd slow down browsing of big directories to the point of it being unusable.

**Comment by musjj** [comment]
Ah, I see. I think you forgot to escape the `?` here (you escape them with `%`, not `\`):

```
> print(string.find("hello:", "^%a[%a%d-_]+:\\?"))
1	6
> print(string.find("hello:", "^%a[%a%d-_]+:\\%?"))
nil
> print(string.find("hello:?", "^%a[%a%d-_]+:\\%?"))
nil
> print(string.find("hello:?", "^%a[%a%d-_]+:%?"))
1	7
```

**Comment by tomasklaen** [comment]
Thx!

**Comment by po5** [comment]
@tomasklaen  
For [memo](https://github.com/po5/memo) I ended up using `^%a[%w.+-]-://` and `^%a[%w.+-]-:%?`, with the same constraints as mpv's own [mp_is_url](https://github.com/mpv-player/mpv/blob/13c6e060e2316d12e34d2983dcc15eecef645900/options/path.c#L356-L373).

**Comment by tomasklaen** [comment]
Thx, I swapped ours with yours.
