### ISSUE TITLE
Don't seek to keyframe when dragging timeline very slowly

### ISSUE THREAD

**Issue by natural-harmonia-gropius** [tomasklaen/uosc#607]
Looks like it always seek to keyframe then exact.

https://github.com/tomasklaen/uosc/assets/50797982/3380abea-0521-4d61-aa55-05780283ee58

**Comment by tomasklaen** [comment]
Seeking by dragging the timeline is using the faster keyframe based seeks, since flooding mpv with exact seek requests didn't seem like a good idea. But I agree that it feels glitchy/bad, and the way the time is jumping around the cursor feels imo worse than just using exact seeks and getting longer response times.

Unless someone comes up with a good reason not to, I think we should do exact seeking here.

**Comment by christoph-heinrich** [comment]
Scrubbing is terrible with exact seeks only

https://github.com/tomasklaen/uosc/assets/8932183/e3a9311a-247a-4221-96eb-1e950b99bb08

https://github.com/tomasklaen/uosc/assets/8932183/21959818-39ef-4212-98b4-2b361c8ee259

We can try to come up with a better way of automatically switching between fast and exact seeks, but I really don't want to loose the automatic switching between those.

**Comment by christoph-heinrich** [comment]
I've made a PR with a possible solution.
You can try adjusting the numbers if you want to.
The `last.time - drag.time > 0.1` in `Timeline:drag_speed()` is for smoothing our measurements. The `0.1` stands for 100ms and you can change it to adjust the filter strength.
The `math.abs(rel_speed) > 0.1` in `Timeline:on_global_mouse_move()` is the threshold for fast seeking. The `0.1` is the dragging speed relative to the timeline width, so 0.1 is 10% of the timeline per second.
