### ISSUE TITLE
Sometimes crashes when repeatedly opening the file menu with the mouse for browsing and clicking

### ISSUE THREAD

**Issue by dyphire** [tomasklaen/uosc#610]
I accidentally triggered this bug while browsing and clicking on the file menu, and the script immediately crashed.
This bug is difficult to reproduce, I need to repeatedly open the file menu with the mouse to browse and click to have a chance to trigger it.
![image](https://github.com/tomasklaen/uosc/assets/61936050/65cb74d7-f6cf-4ff3-965c-8abaa61fa4e3)

**Comment by dyphire** [comment]
I just encountered a new crash prompt while recording a video trying to reproduce the bug.

https://github.com/tomasklaen/uosc/assets/61936050/f1cd3643-f124-4b4c-ace6-2d30dae5b726

![image](https://github.com/tomasklaen/uosc/assets/61936050/8baddf51-b1ef-44c9-979a-53a337f7f0e8)

**Comment by christoph-heinrich** [comment]
I managed to reproduce the first error. The menu needs to be big enough that the playlist/files control overlaps with the menu it opens and I only managed to reproduce it while a local file is open. Repeated fast clicking on the control (and the menu that opens) results in that crash.

What's happening here is that the menu sets `cursor.on_primary_down` (among others), which contains a reference to `self`, then the menu gets closed and `current` gets set to nil (the cause of both crashes). Now if the user clicks before the next render, `cursor.on_primary_down` still has that function calling `self:handle_cursor_down()` while self.current is `nil`.

We need some way of preventing those cursor callbacks from calling closed elements.
We could make `Elements.remove()` call `cursor.reset_handlers`, but that way we might sometimes drop an input event.
We could also turn `cursor.on_primary_down` and friends into queues, where each queued up item is a function and some element reference, so that each element can remove itself from that queue, and as long as some other element has also had a registered callback in that queue, there is still an event handler to fall back on. Not sure if that additional complexity is worth it, considering how rarely the queue might even make a difference.
