### ISSUE TITLE
Can't go back to last playing file (previous file) when shuffle is on

### ISSUE THREAD

**Issue by puffpppp** [tomasklaen/uosc#631]
Is there a way to make shuffle remember what files were played so it follows the same order when going backwards in a playlist?
When going forwards random file should be played but when going to previous, the same file should play which was playing last time, not a random file.

At least this is how it works in other players i'm used to like MPC-HC, MusicBee etc.

In fact they remember the complete order until you toggle shuffle off then on, then they 'forget' all past files.

Ex.

Lets say we have these files:

A,B,C,D,E,F...

I start playing A and turn on shuffle, and now we press next or previous buttons:

Button Pressed --> File Playing
Next  --> D
Next  --> V
Next  --> J
Prev  --> V
Prev  --> D
Next  --> V
Next  --> J
Next  --> X
Toggle shuffle:
Prev  --> Z
Next  --> M
Prev  --> Z

I hope it makes sense what I'm trying to say

**Comment by christoph-heinrich** [comment]
> Toggle shuffle:
Prev --> Z
Next --> M
Prev --> Z

I don't understand that part. We're at X, turn shuffle off, and then the previous one to X should be Z and the one after Z is M???
That shuffles my brain...

**Comment by puffpppp** [comment]
> > Toggle shuffle:
> > Prev --> Z
> > Next --> M
> > Prev --> Z
> 
> That part shuffles my head. We're at X, turn shuffle off, and then the previous one to X should be Z and the one after Z is M???

Idea is that once you toggle Shuffle, the history of all played files is forgotten so there is no previous file to go to in which case a random file is loaded, i.e. Z, then when you press next again a random file is loaded i.e. M
Now pressing prev however there IS a history so Z is played again.

**Comment by christoph-heinrich** [comment]
So with `toggle shuffle` you mean turning it off and on again, right?

**Comment by tomasklaen** [comment]
`prev` commands now play previous files even when shuffle is on, but...

> Idea is that once you toggle Shuffle, the history of all played files is forgotten...

Why should toggling shuffle clean the history? Shuffle controls what file to play next. I wouldn't expect toggling it to wipe my history and essentially _break_ the `prev` button.

**Comment by christoph-heinrich** [comment]
I already whipped up that that same solution locally but it only allows going back once, and repeated going back simply toggles between the last two files.
Going forward after going back also doesn't play the same file that was on that position again.

I think a solution would be to keep a history of shuffling decisions together with the position in that history.
When going back it decrements `shuffle.pos` and uses `shuffle.history[shuffle.pos]`, then when going forward we check if `shuffle.pos` is already at the end of `shuffle.history`, if so it chooses a new random file, otherwise it increments `shuffle.pos` and uses `shuffle.history[shuffle.pos]`.
