### ISSUE TITLE
`animation_factor` is unintuitive

### ISSUE THREAD

**Issue by christoph-heinrich** [tomasklaen/uosc#689]
I understand why it is the way it currently is, but it would be more intuitive if it was some sort of [time constant](https://en.wikipedia.org/wiki/Time_constant). For systems that slowly approach a value (exponential decay i this case) it's typical to use a constant that denotes that there is still 1/e of the way to go (e.g. capacitor charging/discharging curve).

Making that exact would take some more math, but something conceptually similar could be achieved by inverting the current `animation_factor`, so that 0 means no animation, and large values mean a long animation time.

**Comment by tomasklaen** [comment]
Well, it's just a way how you think about it. Factor is how much distance should be covered per tick, 1=all, 0=none. I also tried to have it be a duration and use an easing function, but what I like about the factor is that you can have a moving target and it works seamlessly.

And what do you mean by flipping it exactly? `factor = 1 / option_value`? So that `1` would be instant, and `10` would produce factor `0.1`? That just seems like a different kind, but still an arbitrary value to me.

Maybe we could instead just have `animation_duration` option that is in milliseconds anyway, and then calculate a factor out of that, since we know the animation tick (60hz).

**Comment by christoph-heinrich** [comment]
> And what do you mean by flipping it exactly? `factor = 1 / option_value`? So that `1` would be instant, and `10` would produce factor `0.1`? That just seems like a different kind, but still an arbitrary value to me.

Yes that's what I mean, currently the values for quick animation (0.3) and instant (1) are much further apart then quick (0.3) and infinitely long (0).

> Maybe we could instead just have animation_duration option that is in milliseconds anyway, and then calculate a factor out of that, since we know the animation tick (60hz).

Sure, that's essentially the same concept as the time constant. It's not necessarily 60hz though (`state.render_delay`).

**Comment by tomasklaen** [comment]
As I've mentioned in previous post, I like that factor can have a moving target that can potentially increase or decrease the duration depending on the movement direction. That is incredibly annoying to do with a simple easing based animation which is based on a set duration. I had it implemented when I was adding the `animation_factor` option a couple days ago actually ,and I reverted it because of this.

The current tween implementation already supports this as the target can be a function getter. And moving target might be useful for example if I decide to do the fade-in on cursor entered window thingy, as the animation will be animating towards current relative proximity, which might change with mouse movement while the animation is going on.

**Comment by christoph-heinrich** [comment]
Oh I missed that `to` can also be a function, I was wondering how that moving target should work without restarting the interpolation, in which case it wouldn't matter if it uses the easing function or not.
