### ISSUE TITLE
main.lua opacity

### ISSUE THREAD

**Issue by NitoJV** [tomasklaen/uosc#697]
hi, is there a mistake here?
opacity = {
timeline = ?.9

**Comment by po5** [comment]
Can you elaborate?

This is what he's referring to, I think.
https://github.com/tomasklaen/uosc/blob/7467e182d3f8f8b767677b832fd90f4e9e6c8068/scripts/uosc/main.lua#L188-L189

**Comment by tomasklaen** [comment]
You can omit zero when declaring floating point numbers between 0 and 1. But yeah, the whole codebase is a bit inconsistent in formatting since I stopped using lua formatter due to it one day suddenly stopping doing what it was configured to do. Fixing this and reformatting everything is on my to-do list soon.

**Comment by NitoJV** [comment]
Yes. Because of this, the saturation of the playback time numbers breaks down for me, they become transparent

**Comment by tomasklaen** [comment]
Text is always fully opaque. We never apply opacity to any text (except when it's animating). This is documented above the `opacity` option, which you can use to change opacity of any uosc element background or shape if you disagree with the defaults.
