### ISSUE TITLE
Thumbnails in timeline

### ISSUE THREAD

**Issue by po5** [tomasklaen/uosc#7]
Display thumbnails when hovering the timeline, similar to https://github.com/TheAMM/mpv_thumbnail_script

**Comment by darsain** [comment]
Yes I do wish adding this at some point, but I expect that to have a long ETA.

**Comment by meav** [comment]
I think you should add an option, example: `Thumbnails_in_timeline=false`

**Comment by darsain** [comment]
I did a small writeup on the state of this request in the other issue, but for completeness and everyone that is subscribed to this one, I'll copy it here as well:

---

uosc right now has a codebase that evolved from a simple script that was rendering 2 rectangles, and that is not a good way to design a project. It needs a rewrite, and I don't like the idea of investing a lot of time working on big updates (like thumbnails would definitely be) for a project that needs a rewrite.

There won't be a rewrite either though :( the mpv UI rendering API extremely sucks (it's ASS tags, a subtitles engine, not meant for UI). It's very limited, and has issues like rendering at the same FPS as playing video, so low FPS videos are causing the UI to feel stuttery/lagging behind/slow, and I don't want to put a lot more time into building a UI on top of this.

If I invest a lot of time into mpv UI again, it'll probably be by creating a completely new frontend. mpv+uosc also has a high barrier of entry for an average user, so I'm pretty much spending a lot of development time for a userbase of a couple dozen people, which I also don't like. A more user friendly frontend would fix this. But this might be quite far away from now as I'm working on other projects atm.

This doesn't mean the uosc is dead. I'm still using it every day, and fixing bugs or adding small improvements is not a problem.

That being said, I didn't look into its code, but there shouldn't be a reason for the thumbnail script to not work with uosc. I suspect it stops being displayed because it detects mpv.conf `osc=no` setting which is required for uosc. It'd actually be orders of magnitude easier for the creator of the thumbnail script to implement support for uosc than for me to implement thumbnails. All it needs to do is add a uosc flag and use it's timeline box coordinates (easy since it spans the whole video width) for displaying thumbnails.

**Comment by tomasklaen** [comment]
So here's the current stance:

I've researched existing solutions, and tried to think of some myself, and they all suck. They are either super slow to query the thumbnail, or alternatively they encode the whole file into hundreds of thumbnails to a drive on opening a video so that querying is faster later (when someone has already decided what part to watch and doesn't need fast thumbnails anymore). This causes high CPU usage and laptops flying away just every time someone opens a video.

So unless mpv adds an API that will allow us to query and display a thumbnail without the need to spawn child processes and re-encode the video for a minute, I won't be adding anything like that into uosc.

However, if someone makes a thumbnailing script with API where I can send it a message to display a thumbnail of a queried time at configured position, and another one to hide it when cursor leaves timeline, I won't mind doing that so that masochists who don't mind these thumbnailing solutions can use uosc too.

---

The only alternative solution I kind of liked would be to create and distribute a binary with uosc that would spawn an efficient thumbnailing server and than tell it to generate thumbnails on demand. But even if I'd found a time to make it, I'm not sure if we can spawn and communicate back and forth with a live child process from mpv's lua environment.

**Comment by po5** [comment]
I have been looking into this and have a working proof of concept for thumbnails basically as fast as keyframe seeking, on the fly with low latency and decent memory usage (relative to existing implementations that spawn many mpv processes), for Linux and Windows.

(ugly display for testing)  
https://user-images.githubusercontent.com/42466980/190234102-8b300b56-49e2-4537-9bcb-038e1ab4c52f.mp4

I agree that it should be its own script, with a way for others to order it around. I hope to have something worth publishing in the not too distant future.

**Comment by omaru-ok** [comment]
> I have been looking into this and have a working proof of concept for thumbnails basically as fast as keyframe seeking, on the fly with low latency and decent memory usage (relative to existing implementations that spawn many mpv processes), for Linux and Windows.
> 
> (ugly display for testing) https://user-images.githubusercontent.com/42466980/190234102-8b300b56-49e2-4537-9bcb-038e1ab4c52f.mp4
> 
> I agree that it should be its own script, with a way for others to order it around. I hope to have something worth publishing in the not too distant future.

omg sound good. im lookign for  thumbnail . in near futrure <3

**Comment by christoph-heinrich** [comment]
> I have been looking into this and have a working proof of concept for thumbnails basically as fast as keyframe seeking, on the fly with low latency and decent memory usage (relative to existing implementations that spawn many mpv processes), for Linux and Windows.

Sounds great, how does it work? Will it also work with network streams? I doubt it's possible without any extra network usage.

**Comment by omaru-ok** [comment]
> > I have been looking into this and have a working proof of concept for thumbnails basically as fast as keyframe seeking, on the fly with low latency and decent memory usage (relative to existing implementations that spawn many mpv processes), for Linux and Windows.
> 
> Sounds great, how does it work? Will it also work with network streams? I doubt it's possible without any extra network usage.

yeahh yess . just like how youtube does that . !!

**Comment by tomasklaen** [comment]
@po5 I'd also love to know how it works. If it's efficient and doesn't consume any resources when user is not actively seeking, and doesn't flood the drive with hundreds of thumbnails, I'd use this myself :)

**Comment by po5** [comment]
It can (read: does) work with network streams, but does require its own network cache, I don't think it's worth it considering the memory, latency and bandwidth implications.  
As far as I understand it, yt-dlp can expose video thumbnails (even without an extra call from a script, with the right mpv options). This should be used for YouTube and other services that support thumbnails.

It spawns a hidden mpv with the same file, that gets keyframe seek commands from the ipc.  
Two files are created: one for the ipc socket (virtual on windows), one for transferring requested thumbnail across processes (apparently two-way mpv pipes do not work on windows). No extra temp cache.

If you want to discuss development and not flood this issue, you can reach me on Discord at https://gist.github.com/po5/ba7f443ea90080b2b5ccee7ff7b79023/raw/bb424e0323090942cd27133d69e75f09de001810/discord.txt  
Would be glad to make a group chat to throw ideas around.

**Comment by christoph-heinrich** [comment]
> It can (read: does) work with network streams, but does require its own network cache, I don't think it's worth it considering the memory, latency and bandwidth implications. As far as I understand it, yt-dlp can expose video thumbnails (even without an extra call from a script, with the right mpv options). This should be used for YouTube and other services that support thumbnails.

One last idea (maybe you're already doing that).
When there are no thumbnails available from ytdl, you could use `--format=worst` to save bandwidth or maybe some combination of `format` and `format-sort` to get the video resolution that is closest to the displayed thumbnail.

**Comment by omaru-ok** [comment]
> @po5 I'd also love to know how it works. If it's efficient and doesn't consume any resources when user is not actively seeking, and doesn't flood the drive with hundreds of thumbnails, I'd use this myself :)

hey i found something 

![image](https://user-images.githubusercontent.com/108952834/190248782-82b02840-31d7-4845-b63d-90f83f7d76ea.png)
as he mentioned  herer [beta-release](https://github.com/marzzzello/mpv_thumbnail_script/releases)

idk . i havn't testet that . but sound good too

**Comment by po5** [comment]
Finally figured out the race condition that made the player crash sometimes when rendering the overlay.  
I'll be able to work on making it look nice and add QoL stuff now. Here's hoping for this weekend.  
https://user-images.githubusercontent.com/42466980/190829265-82dea8ee-414e-475a-8ae0-ac94304522fe.mp4

**Comment by omaru-ok** [comment]
> Finally figured out the race condition that made the player crash sometimes when rendering the overlay. I'll be able to work on making it look nice and add QoL stuff now. Here's hoping for this weekend. https://user-images.githubusercontent.com/42466980/190829265-82dea8ee-414e-475a-8ae0-ac94304522fe.mp4

woah

**Comment by tomasklaen** [comment]
This is now implemented as a seamless [thumbfast](https://github.com/po5/thumbfast) integration:

![image](https://user-images.githubusercontent.com/47283320/191493312-7e2da81f-fea8-43f9-8ad8-70c935761ad8.png)
