### ISSUE TITLE
`top_bar` opacity cannot be controlled in `opacity` setting

### ISSUE THREAD

**Issue by FichteFoll** [tomasklaen/uosc#730]
As the title mentions, the opacity of the top bar currently cannot be controlled using the `top_bar` key in the `opacity` setting. It's also not mentioned in the default value. This used to be possible in the previous version (with `top_bar_opacity`) and currently appears to be the only element whose opacity cannot be controlled.

**Comment by FichteFoll** [comment]
Also, just as an FYI, some author credits on the release page mention `@tomas Klaen` instead of `@tomasklaen, which obviously doesn't do the correct thing.

**Comment by tomasklaen** [comment]
`top_bar` refers to the whole top bar thingy including right side controls, and that has no unified opacity prop, but there's `title` for controlling backgrounds of window title, subtitle, and chapter titles.

> Also, just as an FYI, some author credits on the release page mention @tomas Klaen instead of @tomasklaen, which obviously doesn't do the correct thing. And eva needs to be credited as @po5. And andrei Shevcuk as @shvchk.

Damn it. I'm using git-cliff to generate these notes but sometimes it uses author's name instead of the account name and messes it up like that :/ I fixed it manually.

**Comment by FichteFoll** [comment]
Thanks, `title` does it for me. Silly of me to not figure that out on my own.

**Comment by tomas** [comment]
Although I do feel flattered by the credit, I simply cannot accept that honour.

Great work anyway guys!
