### ISSUE TITLE
Updater gives no information about what version you are on; whether update is needed, etc

### ISSUE THREAD

**Issue by Pentaphon** [tomasklaen/uosc#781]
Can we get a more informative update function?  When I press the update function. I'd like to see:

1) What version I am using right now.
2) Whether an update is needed or not. 
3) If an update is needed, a confirmation button to go through with the update.

Right now it just updates itself no matter what which is really not informative.

**Comment by tomasklaen** [comment]
The way it works now is that it just runs the installation commands defined in readme install instructions in the background and reports stdout. Thus, there is no info about new version, if there's a need for an update, or if the command just reinstalled the same version.

Improving the updating by moving it into ziggy (our binary tool that now ships with uosc) is already on my to-do list, but no ETA.

**Comment by tomasklaen** [comment]
We can't update `uosc.conf` without nuking peoples' existing configs. That'll have to remain manual.

**Comment by Solarunit** [comment]
I wish it would be **manual** process : 

- manual check if there is update available, 
- you need to click some update button to update.

**Comment by Pentaphon** [comment]
> I wish it would be **manual** process :

Isn't it already a manual process? I never saw an update notification. Just the update button deep in the menus.

**Comment by Solarunit** [comment]
As a new uosc user, I was't expecting that after clicking on Update item in the menu it will automatically download zip file and install it. I am not a fan of such behavior. I expected to see a menu/window with installed version information and button to Update.

I would also prefer that checking the current release version wasn't automatic, you'll need to click a button to trigger it.

**Comment by Pentaphon** [comment]
@tomasklaen there's been a lot of uosc updates recently. Is there any chance we can get part 1 of this issue resolved by having the uosc main menu show us what version we are currently using?

**Comment by mrfragger** [comment]
this was in the manual a few weeks ago 
add this code to the top of one of your scripts....I add it to blackout.lua

mp.register_script_message('uosc-version', function(version)
	print('uosc version', version)
  end)

then when you start mpv hit ~ for console and it'll show
<img width="244" alt="image" src="https://github.com/user-attachments/assets/1e8061f1-e1c7-4bdf-be9e-732d5452ce81">

**Comment by SideoNaut** [comment]
All I've ever seen when I press Update UOSC is this

![image](https://github.com/user-attachments/assets/9203fd3f-3da5-4b0f-9c9d-a5870222fb7f)

**Comment by SideoNaut** [comment]
All I've ever seen when I click update UOSC in Utils menu is this

![image](https://github.com/user-attachments/assets/3b5fd4a5-d2f5-4fcf-9480-a11ff0bcf3d6)

**Comment by Pentaphon** [comment]
> All I've ever seen when I click update UOSC in Utils menu is this

I've had this issue too and I find it mostly works when I'm playing a video.

**Comment by tomasklaen** [comment]
The updater just tries to run the exact same command that is in the readme install instructions. The known issues are somewhat [documented here](https://github.com/tomasklaen/uosc?tab=readme-ov-file#update). Its very finicky to make this work consistently, and often fails for no reason and no output, as you showed above.

I want to eventually move the updating mechanism to our binary tool, but dunno when I'll find time for that, especially since I want to rewrite it in something that'll produce leaner and less sketchy binaries.

**Comment by tomasklaen** [comment]
Updater now checks for new version and asks whether to update.

![image](https://github.com/user-attachments/assets/ace2c71a-5ce9-49a0-9827-f67d400156d5)

The updating mechanism is still just trying to run a shell command. I was thinking on moving it to the util binary, but dunno what to do about windows where ziggy can't overwrite itself while it's running :/ Something to figure out some other time.

**Comment by Solarunit** [comment]
Thanks! This is huge improvement!

I personally don't use ziggy binaries (there are 3 of them after manual installation). I wish the was an option to ignore ziggy binary installation from the UI?

**Comment by tomasklaen** [comment]
> Upd: tried it in 5.7.0. It relies on ziggy for checking updates.

Yeah, the whole point of ziggy is to allows us to do things in mpv we otherwise can't. Like make http requests to check for updates...

It'll eventually also take over the updating mechanism as well, which should make it a lot more reliable and not bug out all the time in some environments (on macOS it doesn't work at all).

There are 3 binaries because each platform needs a different one. And they are installed all so that your config folder can be synced between platforms and everything just work. I want to eventually rewrite ziggy in something that will produce a bit leaner binaries, but that's just an excuse to learn a different language. The size of current go binaries (~5MB) is not an issue. I prefer this over requiring users to install and manage hundreds of megabytes big python runtimes any day.
