### ISSUE TITLE
How to disable/not show the original mpv.net ico in the media window ?

### ISSUE THREAD

**Issue by adrianmak** [tomasklaen/uosc#812]
i have installed uosc manually
I found that the original mpv.net logo are overlay uosc logo

how to disable original logo ?

**Comment by hooke007** [comment]
It isn't uosc's issue.
You should handle it by mpvnet.

**Comment by christoph-heinrich** [comment]
@stax76

**Comment by Sneakpeakcss** [comment]
[mpv.net options are stored in the file mpvnet.conf](https://github.com/mpvnet-player/mpv.net/blob/main/docs/manual.md#settings)
`show-logo=no`

Weirdly enough only [Chinese](https://github.com/mpvnet-player/mpv.net/blob/8997a2eacbb4ea3adb017566b488e646c40b8bf9/docs/manual_chs.md?plain=1#L530) wiki has this option documented, might be because the newest `mpv.net` doesn't seem to draw that logo anymore, but you should be able to find all of the options in mpv.net's native config menu, it's `c` button by default i think ?
