### ISSUE TITLE
I add a 2x speed button but not working

### ISSUE THREAD

**Issue by blass0009** [tomasklaen/uosc#881]
Hi,

I added `"cycle:fast_forward:speed:1/2!"` to the `controls=` line, but it didn't work.

My expected result is that when this button is pressed, the playback speed changes to 2x and the button is styled as active. When pressed again, the speed changes back to 1x.

However, when this button is pressed, the playback speed does change to 2x, but the button is not styled as activated. Pressing the button again does not change the speed back to 1x.

I tried changing the button to `"cycle:fast_forward:speed:2/1!"`. With this change, pressing the button can change the speed to 1x, but pressing the button again does not change the speed back to 2x.

Additionally, I found that if the playback speed is modified either using the button or the speed slider, the modified playback speed (in my case, 2x) is retained the next time MPV is opened. Adding `"speed=1"` to `mpv.conf` has no effect on this.

Is there a way to set the default speed to 1x when starting MPV?

**Comment by tomasklaen** [comment]
The comparison wasn't working because apparently when observing properties like speed, we receive values like `2.000000`, and that obviously didn't match the expected `2` for us to cycle properly.

Regarding speed being remembered from last time, that's an mpv feature that recalls state for each file when re-opened. Look in mpv docs how to configure it, can't say from the top of my head.
