### ISSUE TITLE
A commit from upstream changed the scaling of uosc?

### ISSUE THREAD

**Issue by hooke007** [tomasklaen/uosc#882]
uosc,scale=4

Current master (mpv)
![image](https://github.com/tomasklaen/uosc/assets/41094733/f6e330f6-00a6-46aa-ab12-8268462750af)

One version I used serveral months ago.
![image](https://github.com/tomasklaen/uosc/assets/41094733/9f7c773a-05ed-4fe1-942b-cb6417b8f4f4)

**Comment by hooke007** [comment]
Everthing seems to be doubled again once I enabled the uosc's scale feature.

**Comment by christoph-heinrich** [comment]
The only related changes I've found are https://github.com/mpv-player/mpv/commit/17d9abd08fb77d3a33b4717b29257a27ee6bab47, https://github.com/mpv-player/mpv/commit/a3648ddac8382e2144feec6485328c6e53ae0062, and https://github.com/mpv-player/mpv/commit/74b4c3c531bd454484ed5d04c9aad0bc531ccd4b. I don't think that any of those are the cause this change in behavior.

Is the current behavior wrong? scale=4 is pretty big, so it makes sense that the UI becomes gigantic.

**Comment by hooke007** [comment]
I just use `4` as a terrible example.
For my 4k display, currently scale=2 already makes everything gigantic (it show as large as scale=4 in the previous version of mpv).

**Comment by hooke007** [comment]
`scale=2` with git master mpv
The size of preview thumbnail is even larger than my context menu of the other softwares...

![PixPin_2024-04-07_23-28-01](https://github.com/tomasklaen/uosc/assets/41094733/69369efa-000f-464a-93ca-64700184beae)
![PixPin_2024-04-07_23-28-13](https://github.com/tomasklaen/uosc/assets/41094733/e3be127a-106f-4a10-9b3e-1e4b2bbf0fdf)

**Comment by christoph-heinrich** [comment]
Ok, but the real question is if it's currently wrong or not.
If you use 2x scaling on your desktop and set 2x scaling in uosc, then 4x scaling is to be expected.
Why did that change? idk, but if it's not currently wrong, then there is nothing to do here imo.

**Comment by hooke007** [comment]
> Ok, but the real question is if it's currently wrong or not.

Wrong

> If you use 2x scaling on your desktop and set 2x scaling in uosc, then 4x scaling is to be expected.

hidpi-window-scale is disabled here. So it shouldn't be scaled again.

**Comment by christoph-heinrich** [comment]
> hidpi-window-scale is disabled here. So it shouldn't be scaled again.

I think `hidpi-window-scale` is for the window size only, not UI scaling.

**Comment by hooke007** [comment]
https://github.com/mpv-player/mpv/commit/a3648ddac8382e2144feec6485328c6e53ae0062

I see. Now `display-hidpi-scale` was reported "correct" with `hidpi-window-scale==no`. But uosc always use it to scale.

**Comment by dyphire** [comment]
> [mpv-player/mpv@a3648dd](https://github.com/mpv-player/mpv/commit/a3648ddac8382e2144feec6485328c6e53ae0062)
> 
> I see. Now `display-hidpi-scale` was reported "correctly" with `hidpi-window-scale==no`. But uosc always use it to scale.

In fact, the current behavior of mpv is more correct.
The `display-hidpi-scale` property should always correctly report the HiDPI scale factorr in order for the script to achieve appropriate scaling. The behavior that was previously disabled with  `hidpi-window-scale=no` options is actually incorrect. What you should do is adjust the parameters to adapt to the new behavior of mpv, which is not an issue of mpv or uosc.

**Comment by hooke007** [comment]
> which is not an issue of mpv or uosc.

But uosc's scaling is designed on the previous behav of hidpi.

**Comment by dyphire** [comment]
> > which is not an issue of mpv or uosc.
> 
> But uosc's scaling is designed on the previous behav of hidpi.

https://github.com/tomasklaen/uosc/blob/e6a5fd981dadcc2a0d30ded64b7bcbd4481692cd/src/uosc/main.lua#L409-L410

From the code perspective, I don't think so. uosc has always set `hidpi_scale` correctly, but due to previous mpv bug, the `hidpi_scale` would fall back to 1.
The additional custom scaling factor provided by uosc is necessary even under the current mpv, as it cannot guarantee that users are using a reasonable hidpi. Custom scaling factors can be adjusted by users themselves. In an ideal scenario, the user's `scale` option should now default to 1.

**Comment by hooke007** [comment]
> fallback to 1 when use hidpi-window-scale=no

Do you mean that the situation was intended to be ignored previously in uosc?

**Comment by dyphire** [comment]
> > fallback to 1 when use hidpi-window-scale=no
> 
> Do you mean that the situation was intended to be ignored previously in uosc?

When was it ignored? It is precisely because of this consideration that we have fallen back to 1. At this point, users need to set their own `scale` options to the appropriate scaling factor.

> as it cannot guarantee that users are using a reasonable HIDPI. Custom scaling factors can be adjusted by users themselves.

It should be said that you ignored this usage scenario, as it was still applicable in previous mpv.

> But uosc's scaling is designed on the previous behav of hidpi.

Your idea that the `scale` option are only designed for this purpose of `hidpi-window-scale=no` is incorrect.
A simple fact is that there is no change in uosc scaling using `hidpi-window-scale=yes` before https://github.com/mpv-player/mpv/commit/a3648ddac8382e2144feec6485328c6e53ae0062 commit and use `hidpi-window-scale=no` after that, indicating that the uosc scaling design is working as expected. The only change is the behavior of mpv, and users who have been using `hidpi-window-scale=no` need to make adjustments, that's all.

**Comment by hooke007** [comment]
I think you didn't get my point.

> Your idea that the scale option are only designed for this purpose of hidpi-window-scale=no is incorrect.

I have no idea why you think so...

**Comment by dyphire** [comment]
> But uosc's scaling is designed on the previous behav of hidpi.

https://github.com/tomasklaen/uosc/blob/e6a5fd981dadcc2a0d30ded64b7bcbd4481692cd/src/uosc/main.lua#L409-L410

If you don't think so, I'm curious about how you came to this conclusion from the code.

**Comment by hooke007** [comment]
>Do you mean that the situation was intended to be ignored previously in uosc?

**Comment by dyphire** [comment]
> > Do you mean that the situation was intended to be ignored previously in uosc?

I have already replied to this. Of course, you can also wait for the developer's response.
