### ISSUE TITLE
Cannot add search results to playlist

### ISSUE THREAD

**Issue by DianaNites** [tomasklaen/uosc#909]
#822 Added the ability to add things to the current playlist, which works great when browsing files and folders within uosc, but not *searching* folders. Search results cannot be added, and the selected search result is reset when attempting to do so with `ctrl+enter`.

possibly related? #841 

[Screencast_20240526_151541.webm](https://github.com/tomasklaen/uosc/assets/5275194/af7b122e-fe40-4114-963d-b518148c3ea8)

**Comment by christoph-heinrich** [comment]
That is because `ctrl+enter` can also be used for submitting a search manually.

@tomasklaen should we change it so that `ctrl+enter` only submits a search when `search_debounce == 'submit'` ?

**Comment by tomasklaen** [comment]
I think we should rethink modifiers a bit:

1. Move appending to playlist to shift.
2. Opening items without closing menu is currently on shift, but it's a rarely useful feature (never needed it myself) to be occupying such a valuable modifier, so that should be moved to something crazy, like ctrl+alt.

**Comment by tomasklaen** [comment]
Adding items to playlist is now on `shift`. Activating without closing the menu is `alt`. Searching now also no longer uses `ctrl+enter` at all, so this issue got fixed from multiple angles.
