### ISSUE TITLE
How to disable scrubbing with the scroll wheel?

### ISSUE THREAD

**Issue by nick-s-b** [tomasklaen/uosc#910]
Hi,
Is there a way to disable scroll-wheel scrubbing when you place the mouse over the progress bar? I find it annoying. I found a way to do it with plain `mpv` osc but it doesn't work with `uosc`.
Thanks!

**Comment by tomasklaen** [comment]
You should set uosc config option `timeline_step` to `0`. Though I've noticed we didn't have a condition that disables it when you do, which is now fixed in the commit above.

**Comment by FichteFoll** [comment]
It appears this change isn't working (anymore)  because setting timeline_step=0 now basically always snaps to the last starting second, which I assume was the previous behavior?

From the code in the referenced commit I would assume that the fix would also allow my usual wheel bindings to take effect, which would be adjusting the volume.

**Comment by Sneakpeakcss** [comment]
https://github.com/tomasklaen/uosc/commit/003f9eeff63c82c16194284a5f1e34ddf4df9ffc broke it

**Comment by tomasklaen** [comment]
Thx for noticing. Fixed.
