### ISSUE TITLE
Add an option to integrate controls with timeline

### ISSUE THREAD

**Issue by larvanitis** [tomasklaen/uosc#914]
Would it be possible to make the controls part of the timeline, so that:

1. They appear/hide together
2. Controls stay visible when the timeline is hovered
3. Controls appear behind time/thumbnail/chapter elements

Of course this could be an opt-in option.

Thanks!

**Comment by tomasklaen** [comment]
1. You mean for controls to be attached to timeline and slide in with it? I had it like that initially, and found it bad UX, because when you're trying to use a control, you start moving the mouse towards it, and it's annoying to aim for something that is changing position as you're moving the cursor. Having them be static and just fade in is more usable.

2.+3. I don't see a good reason for this. It'd just add unnecessary visual noise and make reading the titles harder.

> Of course this could be an opt-in option.

Every option needs to be implemented, maintained, and adds to configuration noise as each user has to read through it in the conf file when they're configuring their setup. In other words, adding an option can often bring more negatives than positives, and this is imo one of those times. Every user has some little nitpick they'd want to add an option for. If we complied with all of them, we'd go crazy maintaining it, and it'd be crazy to try to configure uosc having to read through all of that.

**Comment by larvanitis** [comment]
I fully understand.

Thanks for the extended reply and for the great work you are doing with this project!
