### ISSUE TITLE
question about starting mpv with UI toggled on

### ISSUE THREAD

**Issue by skotarek** [tomasklaen/uosc#922]
okay so I know that I can bind a UI switch to a key with toggle/UI and toggle/elements, but how can i start an mpv instance from the command prompt with the UI enabled by default on startup?

**Comment by tomasklaen** [comment]
There's no built in option to do this, but you could make a script that sends `toggle-ui` command on startup.

**Comment by skotarek** [comment]
> no built in option to do this
are you ever planning on implementing stuff like that?
> you could make a script that sends `toggle-ui` command on startup
I'll give it a try

**Comment by hooke007** [comment]
> but how can i start an mpv instance from the command prompt with the UI enabled by default on startup

There is need to add any codes in uosc or other scripts. mpv can do it https://mpv.io/manual/master/#options-input-commands

**Comment by tomasklaen** [comment]
> are you ever planning on implementing stuff like that?

No, because it'd need additional option, and than figuring out an interaction on how to cancel this "visible on startup" state, which would probably need another option. That's too much configuration fatigue to satisfy one user.

If you want to do niche things like this, you can already do that with existing api. The simplest way being just sending a [`toggle-ui` command](https://github.com/tomasklaen/uosc#toggle-ui) on startup to uosc. If you want this canceled you can send another `toggle-ui`. A more granular and explicit way would be to use the `set-min-visibility <visibility> [<element_ids>]` command. It's documented in the `toggle-ui` docs linked above.

**Comment by skotarek** [comment]
> mpv can do it https://mpv.io/manual/master/#options-input-commands

this works perfectly, thanks
