### ISSUE TITLE
Add "Disabled" option for Subtitle and Audio Menu

### ISSUE THREAD

**Issue by Cananbolt** [tomasklaen/uosc#954]
Currently, the subtitle, and audio menu does not show a disabled option. Is there anyway to enable this?

**Comment by tomasklaen** [comment]
You mean this?

![image](https://github.com/user-attachments/assets/9227c88c-44e6-419d-9272-c238f8f4b59b)

And dunno about audio. Why would you want to disable audio? And how is it different than just muting it?

Or I think I might even remove the disabled option from subtitles as well, and turn activate shortcut into toggle, so that activating currently active track disables it.

**Comment by Cananbolt** [comment]
Yes, that is what I was referring to. I am interested in the disabled option for video (tracks). The reason is so then I am able to activate, another lua script (audio-visualizer).

I am unable to find the code to include all three disabled option (subtitle, audio, and video)? If it is not too much trouble may you please share where I can enable the disable option.

**Comment by tomasklaen** [comment]
You can now disable track in any track type menu (subs, video, audio) by toggling off whatever is currently active.

**Comment by Cananbolt** [comment]
Understood, thank you for the help!
